### ISSUE TITLE
Unfinished?

### ISSUE THREAD

**Issue by Mortimer452** [phelje/updateClickOnce#1]
After installing, I could not find it available as a task on builds or release pipelines, is this extension incomplete?

**Comment by phelje** [comment]
Hi @Mortimer452 this extension is not incomplete what i know of!
Have you intalled it as Azure DevOps Server install or Azure DevOps Services install?

**Comment by Mortimer452** [comment]
I am using TFS 2018 Update 3

**Comment by phelje** [comment]
Do you get any installation log or error messages when installing?

**Comment by phelje** [comment]
Without any more information i can’t help you, and I have not been able to reproduce the issue.
