### ISSUE TITLE
Bug in lastest version: Error if version not set.

### ISSUE THREAD

**Issue by jleed** [phelje/updateClickOnce#3]
The change that was committed a few days ago breaks the build if the version number is not specified. I think conditions in line 37-52 in updateClickOnce/updateClickOnce/Update-ClickOnce.ps1 mean that if you dont specify a version number, it will jump to the " $Version = $Matches[0] " lines and will produce an error.

**Comment by phelje** [comment]
Thanx for your finding, did this a bit to quick to support extraction of version from a string like "DailyBuild-N.N.N.N.
Shuld be solved now.
