### ISSUE TITLE
replacing .deploy files

### ISSUE THREAD

**Issue by jmcmunn** [phelje/updateClickOnce#4]
There is currently an issue where if one of your DLL (or any other) files has the matching token '.deploy' in the middle of the name it gets replaced with '' and then breaks the manifest.  For example if you include a file named Myfile.Deploy.Something.dll then that file gets renamed during the release process, and the step fails.

**Comment by phelje** [comment]
Absolutely!! Replacement was a bit greedy.
Fixed now!
